/*
 * This file is generated by jOOQ.
 */
package moe.crx.jooq.tables.records;


import moe.crx.jooq.tables.Positions;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PositionsRecord extends UpdatableRecordImpl<PositionsRecord> implements Record5<Integer, Integer, Integer, Double, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.positions.id</code>.
     */
    public PositionsRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.positions.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.positions.receipt_id</code>.
     */
    public PositionsRecord setReceiptId(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.positions.receipt_id</code>.
     */
    public Integer getReceiptId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.positions.product_id</code>.
     */
    public PositionsRecord setProductId(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.positions.product_id</code>.
     */
    public Integer getProductId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.positions.price</code>.
     */
    public PositionsRecord setPrice(Double value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.positions.price</code>.
     */
    public Double getPrice() {
        return (Double) get(3);
    }

    /**
     * Setter for <code>public.positions.amount</code>.
     */
    public PositionsRecord setAmount(Integer value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.positions.amount</code>.
     */
    public Integer getAmount() {
        return (Integer) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, Integer, Integer, Double, Integer> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, Integer, Integer, Double, Integer> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Positions.POSITIONS.ID;
    }

    @Override
    public Field<Integer> field2() {
        return Positions.POSITIONS.RECEIPT_ID;
    }

    @Override
    public Field<Integer> field3() {
        return Positions.POSITIONS.PRODUCT_ID;
    }

    @Override
    public Field<Double> field4() {
        return Positions.POSITIONS.PRICE;
    }

    @Override
    public Field<Integer> field5() {
        return Positions.POSITIONS.AMOUNT;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getReceiptId();
    }

    @Override
    public Integer component3() {
        return getProductId();
    }

    @Override
    public Double component4() {
        return getPrice();
    }

    @Override
    public Integer component5() {
        return getAmount();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getReceiptId();
    }

    @Override
    public Integer value3() {
        return getProductId();
    }

    @Override
    public Double value4() {
        return getPrice();
    }

    @Override
    public Integer value5() {
        return getAmount();
    }

    @Override
    public PositionsRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public PositionsRecord value2(Integer value) {
        setReceiptId(value);
        return this;
    }

    @Override
    public PositionsRecord value3(Integer value) {
        setProductId(value);
        return this;
    }

    @Override
    public PositionsRecord value4(Double value) {
        setPrice(value);
        return this;
    }

    @Override
    public PositionsRecord value5(Integer value) {
        setAmount(value);
        return this;
    }

    @Override
    public PositionsRecord values(Integer value1, Integer value2, Integer value3, Double value4, Integer value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PositionsRecord
     */
    public PositionsRecord() {
        super(Positions.POSITIONS);
    }

    /**
     * Create a detached, initialised PositionsRecord
     */
    public PositionsRecord(Integer id, Integer receiptId, Integer productId, Double price, Integer amount) {
        super(Positions.POSITIONS);

        setId(id);
        setReceiptId(receiptId);
        setProductId(productId);
        setPrice(price);
        setAmount(amount);
    }

    /**
     * Create a detached, initialised PositionsRecord
     */
    public PositionsRecord(moe.crx.jooq.tables.pojos.Positions value) {
        super(Positions.POSITIONS);

        if (value != null) {
            setId(value.getId());
            setReceiptId(value.getReceiptId());
            setProductId(value.getProductId());
            setPrice(value.getPrice());
            setAmount(value.getAmount());
        }
    }
}
