/*
 * This file is generated by jOOQ.
 */
package moe.crx.jooq.tables.records;


import java.time.LocalDate;

import moe.crx.jooq.tables.Receipts;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ReceiptsRecord extends UpdatableRecordImpl<ReceiptsRecord> implements Record3<Integer, LocalDate, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.receipts.id</code>.
     */
    public ReceiptsRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.receipts.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.receipts.date</code>.
     */
    public ReceiptsRecord setDate(LocalDate value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.receipts.date</code>.
     */
    public LocalDate getDate() {
        return (LocalDate) get(1);
    }

    /**
     * Setter for <code>public.receipts.organization_id</code>.
     */
    public ReceiptsRecord setOrganizationId(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.receipts.organization_id</code>.
     */
    public Integer getOrganizationId() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, LocalDate, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Integer, LocalDate, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Receipts.RECEIPTS.ID;
    }

    @Override
    public Field<LocalDate> field2() {
        return Receipts.RECEIPTS.DATE;
    }

    @Override
    public Field<Integer> field3() {
        return Receipts.RECEIPTS.ORGANIZATION_ID;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public LocalDate component2() {
        return getDate();
    }

    @Override
    public Integer component3() {
        return getOrganizationId();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public LocalDate value2() {
        return getDate();
    }

    @Override
    public Integer value3() {
        return getOrganizationId();
    }

    @Override
    public ReceiptsRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public ReceiptsRecord value2(LocalDate value) {
        setDate(value);
        return this;
    }

    @Override
    public ReceiptsRecord value3(Integer value) {
        setOrganizationId(value);
        return this;
    }

    @Override
    public ReceiptsRecord values(Integer value1, LocalDate value2, Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ReceiptsRecord
     */
    public ReceiptsRecord() {
        super(Receipts.RECEIPTS);
    }

    /**
     * Create a detached, initialised ReceiptsRecord
     */
    public ReceiptsRecord(Integer id, LocalDate date, Integer organizationId) {
        super(Receipts.RECEIPTS);

        setId(id);
        setDate(date);
        setOrganizationId(organizationId);
    }

    /**
     * Create a detached, initialised ReceiptsRecord
     */
    public ReceiptsRecord(moe.crx.jooq.tables.pojos.Receipts value) {
        super(Receipts.RECEIPTS);

        if (value != null) {
            setId(value.getId());
            setDate(value.getDate());
            setOrganizationId(value.getOrganizationId());
        }
    }
}
