/*
 * This file is generated by jOOQ.
 */
package moe.crx.jooq;


import java.util.Arrays;
import java.util.List;

import moe.crx.jooq.tables.Organizations;
import moe.crx.jooq.tables.Positions;
import moe.crx.jooq.tables.Products;
import moe.crx.jooq.tables.Receipts;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.organizations</code>.
     */
    public final Organizations ORGANIZATIONS = Organizations.ORGANIZATIONS;

    /**
     * The table <code>public.positions</code>.
     */
    public final Positions POSITIONS = Positions.POSITIONS;

    /**
     * The table <code>public.products</code>.
     */
    public final Products PRODUCTS = Products.PRODUCTS;

    /**
     * The table <code>public.receipts</code>.
     */
    public final Receipts RECEIPTS = Receipts.RECEIPTS;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Organizations.ORGANIZATIONS,
            Positions.POSITIONS,
            Products.PRODUCTS,
            Receipts.RECEIPTS
        );
    }
}
