/*
 * This file is generated by jOOQ.
 */
package moe.crx.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Organizations implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Integer inn;
    private final String name;
    private final String giro;

    public Organizations(Organizations value) {
        this.inn = value.inn;
        this.name = value.name;
        this.giro = value.giro;
    }

    public Organizations(
        Integer inn,
        String name,
        String giro
    ) {
        this.inn = inn;
        this.name = name;
        this.giro = giro;
    }

    /**
     * Getter for <code>public.organizations.inn</code>.
     */
    public Integer getInn() {
        return this.inn;
    }

    /**
     * Getter for <code>public.organizations.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Getter for <code>public.organizations.giro</code>.
     */
    public String getGiro() {
        return this.giro;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Organizations other = (Organizations) obj;
        if (this.inn == null) {
            if (other.inn != null)
                return false;
        }
        else if (!this.inn.equals(other.inn))
            return false;
        if (this.name == null) {
            if (other.name != null)
                return false;
        }
        else if (!this.name.equals(other.name))
            return false;
        if (this.giro == null) {
            if (other.giro != null)
                return false;
        }
        else if (!this.giro.equals(other.giro))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.inn == null) ? 0 : this.inn.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.giro == null) ? 0 : this.giro.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Organizations (");

        sb.append(inn);
        sb.append(", ").append(name);
        sb.append(", ").append(giro);

        sb.append(")");
        return sb.toString();
    }
}
