/*
 * This file is generated by jOOQ.
 */
package moe.crx.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Positions implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Integer id;
    private final Integer receiptId;
    private final Integer productId;
    private final Double price;
    private final Integer amount;

    public Positions(Positions value) {
        this.id = value.id;
        this.receiptId = value.receiptId;
        this.productId = value.productId;
        this.price = value.price;
        this.amount = value.amount;
    }

    public Positions(
        Integer id,
        Integer receiptId,
        Integer productId,
        Double price,
        Integer amount
    ) {
        this.id = id;
        this.receiptId = receiptId;
        this.productId = productId;
        this.price = price;
        this.amount = amount;
    }

    /**
     * Getter for <code>public.positions.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Getter for <code>public.positions.receipt_id</code>.
     */
    public Integer getReceiptId() {
        return this.receiptId;
    }

    /**
     * Getter for <code>public.positions.product_id</code>.
     */
    public Integer getProductId() {
        return this.productId;
    }

    /**
     * Getter for <code>public.positions.price</code>.
     */
    public Double getPrice() {
        return this.price;
    }

    /**
     * Getter for <code>public.positions.amount</code>.
     */
    public Integer getAmount() {
        return this.amount;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Positions other = (Positions) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.receiptId == null) {
            if (other.receiptId != null)
                return false;
        }
        else if (!this.receiptId.equals(other.receiptId))
            return false;
        if (this.productId == null) {
            if (other.productId != null)
                return false;
        }
        else if (!this.productId.equals(other.productId))
            return false;
        if (this.price == null) {
            if (other.price != null)
                return false;
        }
        else if (!this.price.equals(other.price))
            return false;
        if (this.amount == null) {
            if (other.amount != null)
                return false;
        }
        else if (!this.amount.equals(other.amount))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.receiptId == null) ? 0 : this.receiptId.hashCode());
        result = prime * result + ((this.productId == null) ? 0 : this.productId.hashCode());
        result = prime * result + ((this.price == null) ? 0 : this.price.hashCode());
        result = prime * result + ((this.amount == null) ? 0 : this.amount.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Positions (");

        sb.append(id);
        sb.append(", ").append(receiptId);
        sb.append(", ").append(productId);
        sb.append(", ").append(price);
        sb.append(", ").append(amount);

        sb.append(")");
        return sb.toString();
    }
}
